module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2f3037",
        "inverse-primary": "#b90067",
        "surface-bright": "#383940",
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#FFB7D5",
        "on-tertiary": "#313030",
        "on-surface-variant": "#e2bdc7",
        "surface-container-low": "#161616",
        "on-error": "#690005",
        "on-secondary-container": "#b7b4b4",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-lowest": "#0a0a0a",
        "outline-variant": "#5a3f48",
        "on-background": "#e2e1eb",
        "surface-container": "#1e1f26",
        "secondary-container": "#474646",
        "secondary-fixed-dim": "#c9c6c5",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed": "#e5e2e1",
        "secondary": "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c8c6c5",
        "outline": "#a98892",
        "background": "#0A0A0A",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#58002e",
        "surface-container-highest": "#33343c",
        "surface-dim": "#111111",
        "surface-variant": "#33343c",
        "on-secondary": "#313030",
        "primary-container": "#FFD6E7",
        "surface-tint": "#FFB7D5",
        "on-surface": "#e2e1eb",
        "tertiary-container": "#929090",
        "error": "#ffb4ab",
        "on-primary": "#640035",
        "surface": "#111111",
        "error-container": "#93000a",
        "on-tertiary-container": "#2a2a2a",
        "tertiary": "#c8c6c5",
        "inverse-surface": "#e2e1eb",
        "surface-container-high": "#282a31",
        "on-primary-fixed-variant": "#8d004e",
        "on-primary-fixed": "#3e001f",
        "primary": "#F4A6C1",
        "primary-fixed": "#FFD6E7",
        "on-tertiary-fixed-variant": "#474746"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "stack-lg": "120px",
        "container-max": "1280px",
        "margin-desktop": "60px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "stack-md": "64px"
      },
      fontFamily: {
        "display-lg-mobile": ["Space Grotesk"],
        "body-md": ["Inter"],
        "display-lg": ["Space Grotesk"],
        "label-caps": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-md": ["Space Grotesk"]
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-lg": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
